Fix gnucash @5.11_0 build failure when +quartz (ticket 66119 gtkmacintegration)
Make gnucash compatible with port gtk-osx-application-common-gtk3 (subport of gtk-osx-application).
The errors came because three GnuCash source files had an import like:
#include <gtkmacintegration/gtkosxapplication.h>
but the include path delivered by port gtk-osx-application-common-gtk3 included the
.../gtkmacintegration/ part. The correct import is:
#include <gtkosxapplication.h>
The affected source files are:
 • gnucash/gnome-utils/gnc-main-window.cpp
 • gnucash/gnome/window-reconcile.cpp
 • libgnucash/core-utils/binreloc.c

Also, gnucash/gnome/CMakeLists.txt did not propagate the include path properly.
CMakeLists.txt must contain a directive like:
target_include_directories(... ${GTK_MAC_INCLUDE_DIRS} )
...to pick up the include dirs discovered by ./CMakeLists.txt:464,
`pkg_check_modules(GTK_MAC IMPORTED_TARGET gtk-mac-integration-gtk3)`.

Fixes ticket 66119 "gnucash @4.11_1: gnc-main-window.c:80:10: fatal error: 'gtkmacintegration/
gtkosxapplication.h' file not found" <https://trac.macports.org/ticket/66119>.
The problem only occurs when port gtk3 has the +quartz variant, because that causes
the GnuCash sources to compile in optional "MAC_INTEGRATION" code.